### ISSUE TITLE
Review this snippet and merge it

### ISSUE THREAD

**Issue by thepeak99** [pondersource/nextcloud-mfa-awareness#58] opened 2023-06-15 10:44 UTC
https://sunet.drive.sunet.se/index.php/s/NnnneoJXFSpCdKf

**Comment by michielbdejong** [comment] 2023-06-26 09:39
[enable_mfa_gss2.1.1.patch](https://github.com/pondersource/nextcloud-mfa-awareness/files/11866771/enable_mfa_gss2.1.1.patch)

**Comment by michielbdejong** [comment] 2023-06-26 10:07
So this patch adds it to the autologin function of the gss slave https://github.com/nextcloud/globalsiteselector/blob/d5d07be/lib/Controller/SlaveController.php#L112
We want to add these lines somewhere in https://github.com/pondersource/mfazones
How should the step-up authentication work?
When you try to access an MFA zone? But these are not discoverable if you're not MFA verified, right?

As @mrvahedi68 said, we can trigger this when the user tries to click the greyed-out 'MFA required or not' settings dialog for a folder

**Comment by mrvahedi68** [comment] 2023-06-26 21:47
I put this patch in `mfazones` application and it was triggered but no dialog shown. this code fired below function from `Manager.php`:
https://github.com/pondersource/server/blob/29470b44a923e82bf4d3c65e63e68b774d5fadcf/lib/private/Authentication/TwoFactorAuth/Manager.php#L392

And as you see there this function only set some config values for user and it will be useful before finishing the login progress. 

[I tested it with `Admin`, another user created by `Admin` that was not in `admin` group, usr1 and usr2]
@michielbdejong @thepeak99

**Comment by michielbdejong** [comment] 2023-11-13 14:58
Duplicate of #72

**Closed by michielbdejong** 2023-11-13 14:58 UTC
