### ISSUE TITLE
Make file owner aware of the MFA verification

### ISSUE THREAD

**Issue by thepeak99** [pondersource/nextcloud-mfa-awareness#59] opened 2023-06-15 10:47 UTC
If the owner is not MFA verified in its current session, they wont be able to change any MFA-related parameter on their own files and resources.

**Comment by michielbdejong** [comment] 2023-06-15 11:08
As phrased in https://git.radicallyopensecurity.com/ros/pen-sunet-mfa-zones/-/issues/2 :
> enable `mfazones` setting only for mfa-authenticated users.

**Comment by michielbdejong** [comment] 2023-06-26 09:28
Duplicate of #61

**Closed by michielbdejong** 2023-06-26 09:28 UTC
